<?php

namespace AppBundle\Repository;

/**
 * CategorieProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList(
        $recherche_par, 
        $a_rechercher
    )
    {
        $em = $this->getEntityManager();
        
        $query = "  select *
                    from categorie_produit cp
                    where cp.nom is not null ";

        $query .= " order by cp.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
