<?php

namespace AppBundle\Repository;

/**
 * CompteBancaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteBancaireRepository extends \Doctrine\ORM\EntityRepository
{
	public function list($recherche_par,$a_rechercher)
	{

		$em = $this->getEntityManager();
		
		$query = "	select cb.id as id, b.nom as banque, cb.num_compte, cb.solde
					from compte_bancaire cb
					inner join banque b on (cb.banque = b.id)";

		$where = " where b.id is not null";

		if ($recherche_par == 1) {
			$where .= "	and b.nom like '%". $a_rechercher ."%'";
		}

		if ($recherche_par == 2) {
			$where .= "	and cb.num_compte like '%". $a_rechercher ."%'";
		}

		$query .= $where;

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;

	}

	public function listByBanque($id_banque)
	{

		$em = $this->getEntityManager();
		
		$query = "	select cb.id as id, cb.num_compte
					from compte_bancaire cb
					inner join banque b on (cb.banque = b.id)
					where b.id = " . $id_banque;

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;

	}
}