<?php

namespace AppBundle\Repository;

/**
 * FactureServiceDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureServiceDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
