<?php

namespace AppBundle\Repository;

/**
 * FactureProduitDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureProduitDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
