<?php

namespace AppBundle\Repository;

/**
 * ModelePdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelePdfRepository extends \Doctrine\ORM\EntityRepository
{
	public function list()
	{

		$em = $this->getEntityManager();
		
		$query = "	select *
					from modele_pdf mp
					order by mp.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;

	}
}
