<?php

namespace AppBundle\Repository;

/**
 * PaiementCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementCreditRepository extends \Doctrine\ORM\EntityRepository
{
}
