<?php

namespace AppBundle\Repository;

/**
 * PannierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PannierRepository extends \Doctrine\ORM\EntityRepository
{
}
