<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
	public function list($agence)
	{
		$em = $this->getEntityManager();
		
		$query = "	select *
					from produit p
					where p.nom is not null ";

		if ($agence) {
			$query .= "	and p.agence = " . $agence ;
		}

		$query .= "	order by p.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
	}
}
