<?php

namespace AppBundle\Repository;

/**
 * RavitaillementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RavitaillementRepository extends \Doctrine\ORM\EntityRepository
{
}
